name: disnake-hello

volumes:
  data:
  logs:

services:
  core:
    container_name: core
    image: jlgingrich/disnake
    build:
      dockerfile_inline: |
        COPY ./exts ./exts
        RUN pip install -r requirements.txt
    env_file:
      - .env
    volumes:
      - data:/app/data
      - logs:/app/logs